services:
  - type: web
    name: crackaid-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: 7805668215:AAGmEvmdBcDHfajno84eIaQhF-fadoWfW7A
